# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo:7.0.1-rc0
    restart: always
    volumes:
      - ../mongodb:/data/mongodb
      - /etc/timezone:/etc/timezone:ro
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: john
      MONGO_INITDB_ROOT_PASSWORD: john

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: john
      ME_CONFIG_MONGODB_ADMINPASSWORD: john
      ME_CONFIG_MONGODB_URL: mongodb://john:john@mongo:27017/
